from vector import Vector

v1 = Vector([2.0, 5.0, 6.0])
v1s = Vector([1.0, 2.0, 4.0])
v1n = Vector([2.0, 5.0])

print("print v1 values\n", v1.values)
print("print v1 shape\n", v1.shape)
print()
v2 = Vector([[0.0], [1.0], [2.0], [3.0]])
print("print v2 values\n", v2.values)
print("print v2 shape\n", v2.shape)
print("")
v3 = Vector((10, 15))
print("print v3 values\n", v3.values)
print("print v3 shape\n", v3.shape)
print("")
v4 = Vector(3)
print("print v4 values\n", v4.values)
print("print v4 shape\n", v4.shape)
v4t = v4.T()
print("print transpose v4\n", v4t.values)
v4tb = v4t.T()
print("print transpose back v4\n", v4tb.values)
print("dot product of v2 and v2, same shape:", v2.dot(v2))
print()
print("dot product of v4t and v2 not same shape:", v4t.dot(v2))
print()
vplus = Vector(1)
vplus = v1 + v1n
print("not nested: v1 + v1n =", vplus.values)

vplus = v1 + v1
vn = Vector([[2.0], [5.0], [6.0]])
print("here is v1 and vn\nv1", v1.values, "\nvn", vn.values)
print()
print("not nested: v1 + v1 =", vplus.values)
print()
vplus = vn.__radd__(vn)
print("nested: vn + vn =", vplus.values)
print()
vsub = v1.__rsub__(v1s)
print("non nested: v1 - v1s =", vsub.values)
print()
vdiv = v1 / 2
print("div: v1 / 2 =", vdiv.values)
print()
vmul = v1 * 2
print("multi: v1 * 2 =", vmul.values)
print()
print("__str__")
print(v1)
print("__repr__")
print(str([v1]))
